#!/usr/bin/python
# -*- encoding: utf8 -*-

# use python 2
# install tabulate

"""
TODO:
    ignore empty lines

"""
import os
import re
import sys
from tabulate import tabulate
import argparse


# "Configuration", because the interpreter is a better config file reader than
# one that I will ever write.
FILETYPES = [".py", ".java", ".jsp", ".sql", ".tag", ".md", ".sln"]
FRONTEND = [".jsp"]
BACKEND = [".java"]

# --------------
# Stat functions
# --------------

def sh(command):
    return os.popen(command + " 2>/dev/null").read()

def is_valid_filetype(file):
    for ft in FILETYPES:
        if ft in file:
            return True
    return False

def contrib_percentage(names, filetypes):
    files = []

    for ft in filetypes:
        files += sh("find . -type f -name \"*" + ft + "\"").split("\n")

    files = filter(None, files)

    blame = ""

    for f in files:
        command = "git blame " + f
        blame += sh(command)

    total = len(blame.split("\n"))

    blame_contrib_parser(blame, names, total)
    front_back_parser(files, names)

# parses git blame output to count output
def blame_contrib_parser(blame, names, total):
    results = []
    for name in names:
        numlines = 0
        for l in blame.split("\n"):
            if name in l:
                numlines += 1
        results.append([name, numlines, str(round((float(numlines) / total) * 100.0, 1)) + "%"])

    results.sort(key=lambda x: x[1])
    results = reversed(results)

    print "\n[-dc] Total lines of code per person out of the total " + str(total) + " lines in the project:\n"
    print tabulate(results, headers=["name", "lines", "%"], tablefmt='orgtbl')
    return results

def front_back_parser(files, names):
    fullstack = {} # {author: [front, end]}

    for name in names:
        fullstack[name] = [0, 0]

    total_front = 0
    total_back = 0

    for f in files:
        blame = sh("git blame " + f)

        type = -1 # unknown


        for filetype in FRONTEND:
            if filetype in f:
                type = 0 # frontend
                total_front += len(blame.split("\n"))
        for filetype in BACKEND:
            if filetype in f:
                type = 1 # backend
                total_back += len(blame.split("\n"))


        if type is -1:
            #print f,("is neither frontend nor backend.");
            continue

        for line in blame.split("\n"):
            for name in names:
                if name in line:
                    fullstack[name][type] += 1

    tablist = []
    for author in fullstack:
        back_lines = fullstack[author][1] * (total_front / float(total_back))
        front_share = round((fullstack[author][0] / (fullstack[author][0] + \
            float(back_lines))) * 100, 2)

        tablist.append([author, fullstack[author][0], front_share, \
            fullstack[author][1], 100 - front_share, get_dev_type(front_share)])

    tablist.sort(key=lambda x: x[2])

    total_full = float(total_back + total_front)
    print "\nYour project is", total_back, \
        "lines (" , round((total_back / total_full) * 100, 2), \
        "% ) backend and", total_front, \
        "lines (", round((total_front / total_full) * 100, 2), "% ) frontend.",\
        "\nThis is how those lines are distributed over the contributors:\n",\
        "  (The backend contributions are scaled to the size of the frontend, this eliminates the bias\n"\
        "  to the larger of the two components.)\n"

    print tabulate(tablist, headers=["name", "frontend", "%", "backend", "%", "type"], tablefmt='orgtbl')


def get_dev_type(front_share):
    if front_share >= 80 and front_share <= 100:
        return "Frontend"

    if front_share >= 60 and front_share <= 80:
        return "Mostly frontend"

    if front_share >= 40 and front_share <= 60:
        return "Full stack"

    if front_share >= 20 and front_share <= 40:
        return "Mostly backend"

    if front_share >= 0  and front_share <= 20:
        return "Backend"

def lines_per_commit(FILETYPES):
    authors = {}

    gitlog = sh("git log --stat")
    commit_stats = re.split(r"(commit [0-9,a-f]{40})", gitlog)

    commit_hashes = re.findall(r"(commit [0-9,a-f]{40})", gitlog)


    commits = []

    i = 0
    while i < len(commit_stats) - 1:
        commits.append(commit_stats[i - 1] + commit_stats[i])
        i += 2

    # because instead of doing the above properly, I'm hacking this together
    del commits[0]

    commit_dict = {}

    for c in commits:
        lines = 0
        split_msg = c.split("\n")

        if len(split_msg) < 2:
            continue

        author = get_author(split_msg[0].split(" ")[1][0:40])

        hash = split_msg[0].split(" ")[1]

        for s in split_msg[5:len(split_msg)]:
            if "MERGE" in s.upper():
                break

            lines = s.replace(" ", "").split("|")
            if len(lines) == 2:
                if "Bin" not in lines[1] and is_valid_filetype(lines[0]):
                    #commit_dict[hash] = [author, re.match("[0-9]+", lines[1]).group()]
                    numlines = int(re.match("[0-9]+", lines[1]).group())
                    if hash in commit_dict:
                        commit_dict[hash][0] = author
                        commit_dict[hash][1] += numlines
                    else:
                        commit_dict[hash] = [author, numlines]

    return commit_dict


def total_additions_deletions(FILETYPES):
    commit_dict = lines_per_commit(FILETYPES)

    authors = {}

    for hash in commit_dict:
        author = commit_dict[hash][0]
        lines = commit_dict[hash][1]
        if author in authors:
            authors[author] += lines
        else:
            authors[author] = lines

    tablist = []
    for a in authors:
        tablist.append([a, authors[a]])

    tablist.sort(key=lambda x: x[1])
    tablist = reversed(tablist)

    print "\n\n[-dt] Sum of all additions and deletions:\n"
    print tabulate(tablist, headers=["name", "add/del"], tablefmt='orgtbl')


def avg_lines_per_commit(FILETYPES):
    commits = lines_per_commit(FILETYPES)

    result = {}

    for commit in commits:
        author = commits[commit][0]
        numlines = commits[commit][1]

        if author in result:
            result[author][0] += 1
            result[author][1] += numlines
        else:
            result[author] = [1, numlines]

    tablist = []
    for r in result:
        num_commits = result[r][0]
        num_lines = result[r][1]
        tablist.append([r, num_commits, num_lines, round(float(num_lines) / num_commits, 1)])

    tablist.sort(key=lambda x: x[3])

    print "\n\n[-da] Number of commits, additions/deletions and lines/commit:\n"
    print tabulate(tablist, headers=["name", "commits", "add+del", "l/c"], tablefmt='orgtbl')


def is_correct_commit_msg(msg):
    subject = msg.split("\n")[0]

    if len(msg) == 0:
        return "Correct."

    # First letter must be capital
    if msg[0] == msg[0].lower():
        return "First letter must be capital."

    # Last character cannot be punctuation
    last_c = subject[len(subject) - 1]
    if last_c in "!?.,(":
        return "Last character must not be punctuation."

    # Second letter cannot be caps (prevents all caps msgs)
    if msg[1] == msg[1].upper():
        return "Wrong capitalization."

    # First word must be imperative (can't be checked with 100% certainty)
    first_w = msg.split(" ")[0]
    if first_w[len(first_w) - 2] + first_w[len(first_w) - 1] == "ed" and \
            first_w not in ["Need"]:
        return "First word must be imperative."

    # Message must not be longer than 50 characters
    if len(msg.split("\n")[0]) > 50:
        return "Subject line must not be longer than 50 characters."

    return "Correct."


def get_author(hash):
    raw = sh("git log " + hash + " | head -n 4")
    raw = raw.split("\n")
    for line in raw:
        if line.startswith("Author"):
            return line.split(": ")[1].split("<")[0]

def get_message(hash):
    msg = sh("git log " + hash + " -n 1 | grep \"    \"")
    return msg.replace("    ", "")

def wrong_commit_msgs(NAMES):
    # commits_raw = os.popen("git log --oneline | grep -v Merge").read().split("\n")
    #
    # commits = {} # {hash: msg}
    #
    # for c in commits_raw:
    #     splitc = c.split(" ")
    #
    #     if len(splitc) <= 1:
    #         continue
    #
    #     hash = splitc[0]
    #     msg = " ".join(splitc[1:])
    #     commits[hash] = msg

    commits = {} # {hash: msg}
    mistakes = {} # {mistake: count}
    mistakes["First letter must be capital."]                       = 0
    mistakes["Last character must not be punctuation."]             = 0
    mistakes["Wrong capitalization."]                               = 0
    mistakes["First word must be imperative."]                      = 0
    mistakes["Subject line must not be longer than 50 characters."] = 0

    hashes = map(str.strip, sh("git log --oneline | grep -v Merge").split("\n"))

    for i in range(0, len(hashes)):
        hashes[i] = hashes[i].split(" ")[0]

    for hash in hashes:
        msg = get_message(hash)

        if "Merge" in msg:
            continue

        commits[hash] = msg

    authors = {} # {name: [good, bad]}

    for name in NAMES:
        authors[name] = [0, 0]

    for commit in commits:
        msg = commits[commit]
        author = get_author(commit)

        correctness = is_correct_commit_msg(msg)

        if "Correct." in correctness:
            authors[author][0] += 1 # correct commit
        else:
            authors[author][1] += 1 # wrong commit
            mistakes[correctness] += 1
            if args.wrong:
                print commit + " " + author + ":"
                print "--> " + correctness + "\n"
                print msg


    tablist = []
    for a in authors:
        correct = authors[a][0]
        wrong =  authors[a][1]
        ratio = 0
        if wrong == 0:
            ratio = "inf"
        else:
            ratio = round(float(correct) / wrong, 2)

        tablist.append([a, correct, round(wrong, 0), ratio])

    tablist.sort(key=lambda x: x[3])
    tablist = reversed(tablist)

    print "\n\n[-dm] Number of correct commits, incorrect commits, and ratio (higher is better):"
    print "Since the correctness of a commit message depends on some language rules, this occasionally gives some false positives\n"
    print tabulate(tablist, headers=["name", "correct", "wrong", "ratio"], tablefmt='orgtbl')

    mistakelist = []
    for mistake in mistakes:
        mistakelist.append([mistake, mistakes[mistake]])

    mistakelist.sort(key = lambda x: x[1])
    mistakelist = reversed(mistakelist)

    print "\n\nMistakes made in commit messages in this project:\n"
    print tabulate(mistakelist, headers=["mistake", "count"], tablefmt='orgtbl')


# -----------
# Preparation
# -----------

parser = argparse.ArgumentParser()

parser.add_argument("-w", "--wrong", help="display for all users their erroneous commits",
                    action="store_true")
parser.add_argument("-dc", "--disable-contrib",
    help="disable contribution to end product percentage stat", action="store_true")
parser.add_argument("-dt", "--disable-totals",
    help="disable total additions and deletions stat", action="store_true")
parser.add_argument("-da", "--disable-average",
    help="disable average lines per commit stat", action="store_true")
parser.add_argument("-dm", "--disable-messages",
    help="disable message analyzer", action="store_true")

parser.add_argument("-c", "--enable-contrib",
    help="enable contribution to end product percentage stat", action="store_true")
parser.add_argument("-t", "--enable-totals",
    help="enable total additions and deletions stat", action="store_true")
parser.add_argument("-a", "--enable-average",
    help="enable average lines per commit stat", action="store_true")
parser.add_argument("-m", "--enable-messages",
    help="enable message analyzer", action="store_true")

parser.add_argument("-f", "--fullstack",
    help="shows how much everyone contributed to the front and backend", action="store_true")

args = parser.parse_args()

if not sh("git rev-parse --is-inside-work-tree").startswith("true"):
    print "Not in a git repository."
    sys.exit()

print ""

NAMES = []

for author in os.popen("git log | grep Author").read().split("\n"):
    name = ""
    try:
        name = author.split(": ")[1].split("<")[0].encode('ascii', 'ignore')
    except:
        continue

    if name not in NAMES:
        NAMES.append(name)


# ---------
# Execution
# ---------
show_all = False
for arg in vars(args):
    if "enable" in arg or "disable" in arg:
        show_all = show_all or getattr(args, arg)

show_all = not show_all

do_contrib = (not args.disable_contrib and args.enable_contrib) or show_all
do_totals = (not args.disable_totals and args.enable_totals) or show_all
do_average = (not args.disable_average and args.enable_average) or show_all
do_messages = (not args.disable_messages and args.enable_messages) or show_all

if do_contrib:
    contrib_percentage(NAMES, FILETYPES)

if do_totals:
    total_additions_deletions(FILETYPES)

if do_average:
    avg_lines_per_commit(FILETYPES)

if do_messages:
    wrong_commit_msgs(NAMES)
