#!/usr/bin/python

import os
import sys
import re

rawData = os.popen("upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage").read().split(" ")
percentage = int(re.sub("[^0-9]", "", filter(None, rawData)[1]))

if (percentage < 100):
    os.popen("notify-send 'Battery low! (" + str(percentage) + "%)'")

print str(percentage)
