#!/bin/bash

#xrandr --output DP-1 --right-of eDP-1
#xrandr --output DP-1 --primary --output eDP-1 --right-of DP-1
#Dual
#xrandr --output DP-1 --primary --output eDP-1 --left-of DP-1
#Duplicate
#xrandr --output eDP-1-1 --auto --output DP-1 --auto --same-as eDP-1-1
xrandr --output DP-1 --primary --output eDP-1-1 --left-of DP-1
