#!/usr/bin/python

from __future__ import division
import time
import os

rawCommand = os.popen("df | grep '/dev/nvme0n1p4'").read().split(' ')

sizeIndex = 0
usedIndex = 0
for i in range(1, len(rawCommand)):
    if (rawCommand[i] != ""):
       if sizeIndex == 0:
           sizeIndex = i
       elif sizeIndex != 0:
           usedIndex = i
           break


totalStorage = round(int(rawCommand[sizeIndex]) / 1024.0 / 1024.0, 1)
full = round(int(rawCommand[usedIndex]) / 1024.0 / 1024.0, 1)

print full

