#!/usr/bin/python

import os
import sys
import re

total_ram = 8.0 # In GB
ram_usage_crit = total_ram - 0.5
ram_usage_warn = total_ram - 2
ram_usage_low = total_ram / 4

raw_data = os.popen("free -m | grep Mem").read()
data_list = raw_data.split(' ')
results = filter(None, data_list)
usedmem = results[2]
print(usedmem)

q = re.compile('\d+,?\d+')
digits_only = q.match(results[len(results) - 5]).group()
result_float = float(digits_only.replace(',','.'))

