#!/usr/bin/python3

import datetime, os

midnight = float(os.popen("date -d 'today 00:00:00' \"+%s.%N\"").read())
now = float(os.popen("date \"+%s.%N\"").read())

form = "{:3.0f}"

seconds = now - midnight

h = ((seconds / 60.0) / 60)
m = (seconds - int(h) * 60 * 60) / 60.0

h_angle = (h % 12) / 12.0 * 360
m_angle = (m / 60.0) * 360
s_angle = ((seconds % 60) / 60.0) * 360

am_pm = "AM"
if h > 12:
    am_pm = "PM"

print((form + "° " + form + "° " + form + "° {}").format(h_angle, m_angle, s_angle, am_pm))
