#!/usr/bin/python3

import datetime, os

form = "{:3.0f}"
do_secs = False
do_mins = False

midnight = float(os.popen("date -d 'today 00:00:00' \"+%s.%N\"").read())
now = float(os.popen("date \"+%s.%N\"").read())
seconds = now - midnight

h = ((seconds / 60.0) / 60)
m = (seconds - int(h) * 60 * 60) / 60.0

h_angle = (h % 12) / 12.0 * 360
m_angle = (m / 60.0) * 360
s_angle = ((seconds % 60) / 60.0) * 360

am_pm = "AM"
if h > 12:
    am_pm = "PM"


h_str = (form + "° ").format(h_angle)
m_str = ""
if do_mins:
    m_str = (form + "° ").format(m_angle)
s_str = ""
if do_secs:
    s_str = (form + "° ").format(s_angle)

print((h_str + m_str + s_str + "{}").format(am_pm))
