#!/bin/bash

pdf=$(curl -s https://www.utwente.nl/nl/cfm/diensten-abc-bijlages/catering/restaurant-waaier/ | grep "[\:\./0-9a-Z\-]*.pdf" -o | grep "week\-$(date +%-V)" | head -n 1)

wget $pdf -O /tmp/eten.pdf -nv -q

pdf2txt -o /tmp/output.txt /tmp/eten.pdf

oldlang=$LANG

LANG=en_US
cat /tmp/output.txt | grep "$(date +%A)" -A 14

LANG=$oldlang
rm /tmp/output.txt /tmp/eten.pdf
